### ISSUE TITLE
hex mode

### ISSUE THREAD

**Issue by auscompgeek** [keepcalm444/machinecode.py#3]
The real emulators on OpenLearning have a hexadecimal mode. (The default is decimal mode.)

**Comment by fourkbomb** [comment]
if you want it, do it yourself.

**Comment by auscompgeek** [comment]
m8.

**Comment by gnustomp** [comment]
A slightly ruder way to say "patches welcome"? Huh.

**Comment by auscompgeek** [comment]
Ah, I knew there was a reason why I forked this. I just couldn't remember until today when I went inbox diving.
